# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :distribute do
    increment_build_number
    firebase_app_distribution(
      app: "1:25340735056:ios:b185bc56fc157eeb56ab55",
      testers: "thanedpon.top@hotmail.com, thanedpon_k@tripetch-it.co.th",
      groups: "dev-team",
      firebase_cli_path: "/usr/local/bin/firebase"
    )
  end
end
