# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
    gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end

lane :playstore do
  build_android_app(task: "assembleRelease")
  # submit build to firebase app distribution
  firebase_app_distribution(
            app: "1:25340735056:android:a7b368e5d586bc6156ab55",
            testers: "thanedpon.top@hotmail.com, thanedpon_k@tripetch-it.co.th",
            apk_path: "app/build/outputs/apk/debug/app-debug.apk",
            groups: "dev-team",
            firebase_cli_path: "/usr/local/bin/firebase"
        )
end
